// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/pivotal-cf/on-demand-service-broker/broker"
	"github.com/pivotal-cf/on-demand-service-broker/task"
	"github.com/pivotal-cf/on-demand-services-sdk/serviceadapter"
)

type FakeODBSecrets struct {
	GenerateSecretPathsStub        func(deploymentName, manifest string, secretsMap serviceadapter.ODBManagedSecrets) []broker.ManifestSecret
	generateSecretPathsMutex       sync.RWMutex
	generateSecretPathsArgsForCall []struct {
		deploymentName string
		manifest       string
		secretsMap     serviceadapter.ODBManagedSecrets
	}
	generateSecretPathsReturns struct {
		result1 []broker.ManifestSecret
	}
	generateSecretPathsReturnsOnCall map[int]struct {
		result1 []broker.ManifestSecret
	}
	ReplaceODBRefsStub        func(manifest string, secrets []broker.ManifestSecret) string
	replaceODBRefsMutex       sync.RWMutex
	replaceODBRefsArgsForCall []struct {
		manifest string
		secrets  []broker.ManifestSecret
	}
	replaceODBRefsReturns struct {
		result1 string
	}
	replaceODBRefsReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeODBSecrets) GenerateSecretPaths(deploymentName string, manifest string, secretsMap serviceadapter.ODBManagedSecrets) []broker.ManifestSecret {
	fake.generateSecretPathsMutex.Lock()
	ret, specificReturn := fake.generateSecretPathsReturnsOnCall[len(fake.generateSecretPathsArgsForCall)]
	fake.generateSecretPathsArgsForCall = append(fake.generateSecretPathsArgsForCall, struct {
		deploymentName string
		manifest       string
		secretsMap     serviceadapter.ODBManagedSecrets
	}{deploymentName, manifest, secretsMap})
	fake.recordInvocation("GenerateSecretPaths", []interface{}{deploymentName, manifest, secretsMap})
	fake.generateSecretPathsMutex.Unlock()
	if fake.GenerateSecretPathsStub != nil {
		return fake.GenerateSecretPathsStub(deploymentName, manifest, secretsMap)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.generateSecretPathsReturns.result1
}

func (fake *FakeODBSecrets) GenerateSecretPathsCallCount() int {
	fake.generateSecretPathsMutex.RLock()
	defer fake.generateSecretPathsMutex.RUnlock()
	return len(fake.generateSecretPathsArgsForCall)
}

func (fake *FakeODBSecrets) GenerateSecretPathsArgsForCall(i int) (string, string, serviceadapter.ODBManagedSecrets) {
	fake.generateSecretPathsMutex.RLock()
	defer fake.generateSecretPathsMutex.RUnlock()
	return fake.generateSecretPathsArgsForCall[i].deploymentName, fake.generateSecretPathsArgsForCall[i].manifest, fake.generateSecretPathsArgsForCall[i].secretsMap
}

func (fake *FakeODBSecrets) GenerateSecretPathsReturns(result1 []broker.ManifestSecret) {
	fake.GenerateSecretPathsStub = nil
	fake.generateSecretPathsReturns = struct {
		result1 []broker.ManifestSecret
	}{result1}
}

func (fake *FakeODBSecrets) GenerateSecretPathsReturnsOnCall(i int, result1 []broker.ManifestSecret) {
	fake.GenerateSecretPathsStub = nil
	if fake.generateSecretPathsReturnsOnCall == nil {
		fake.generateSecretPathsReturnsOnCall = make(map[int]struct {
			result1 []broker.ManifestSecret
		})
	}
	fake.generateSecretPathsReturnsOnCall[i] = struct {
		result1 []broker.ManifestSecret
	}{result1}
}

func (fake *FakeODBSecrets) ReplaceODBRefs(manifest string, secrets []broker.ManifestSecret) string {
	var secretsCopy []broker.ManifestSecret
	if secrets != nil {
		secretsCopy = make([]broker.ManifestSecret, len(secrets))
		copy(secretsCopy, secrets)
	}
	fake.replaceODBRefsMutex.Lock()
	ret, specificReturn := fake.replaceODBRefsReturnsOnCall[len(fake.replaceODBRefsArgsForCall)]
	fake.replaceODBRefsArgsForCall = append(fake.replaceODBRefsArgsForCall, struct {
		manifest string
		secrets  []broker.ManifestSecret
	}{manifest, secretsCopy})
	fake.recordInvocation("ReplaceODBRefs", []interface{}{manifest, secretsCopy})
	fake.replaceODBRefsMutex.Unlock()
	if fake.ReplaceODBRefsStub != nil {
		return fake.ReplaceODBRefsStub(manifest, secrets)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.replaceODBRefsReturns.result1
}

func (fake *FakeODBSecrets) ReplaceODBRefsCallCount() int {
	fake.replaceODBRefsMutex.RLock()
	defer fake.replaceODBRefsMutex.RUnlock()
	return len(fake.replaceODBRefsArgsForCall)
}

func (fake *FakeODBSecrets) ReplaceODBRefsArgsForCall(i int) (string, []broker.ManifestSecret) {
	fake.replaceODBRefsMutex.RLock()
	defer fake.replaceODBRefsMutex.RUnlock()
	return fake.replaceODBRefsArgsForCall[i].manifest, fake.replaceODBRefsArgsForCall[i].secrets
}

func (fake *FakeODBSecrets) ReplaceODBRefsReturns(result1 string) {
	fake.ReplaceODBRefsStub = nil
	fake.replaceODBRefsReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeODBSecrets) ReplaceODBRefsReturnsOnCall(i int, result1 string) {
	fake.ReplaceODBRefsStub = nil
	if fake.replaceODBRefsReturnsOnCall == nil {
		fake.replaceODBRefsReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.replaceODBRefsReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeODBSecrets) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.generateSecretPathsMutex.RLock()
	defer fake.generateSecretPathsMutex.RUnlock()
	fake.replaceODBRefsMutex.RLock()
	defer fake.replaceODBRefsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeODBSecrets) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ task.ODBSecrets = new(FakeODBSecrets)
