// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"log"
	"sync"

	"github.com/pivotal-cf/brokerapi"
	"github.com/pivotal-cf/on-demand-service-broker/broker"
	"github.com/pivotal-cf/on-demand-services-sdk/bosh"
	"github.com/pivotal-cf/on-demand-services-sdk/serviceadapter"
)

type FakeServiceAdapterClient struct {
	CreateBindingStub        func(bindingID string, deploymentTopology bosh.BoshVMs, manifest []byte, requestParams map[string]interface{}, secretsMap map[string]string, logger *log.Logger) (serviceadapter.Binding, error)
	createBindingMutex       sync.RWMutex
	createBindingArgsForCall []struct {
		bindingID          string
		deploymentTopology bosh.BoshVMs
		manifest           []byte
		requestParams      map[string]interface{}
		secretsMap         map[string]string
		logger             *log.Logger
	}
	createBindingReturns struct {
		result1 serviceadapter.Binding
		result2 error
	}
	createBindingReturnsOnCall map[int]struct {
		result1 serviceadapter.Binding
		result2 error
	}
	DeleteBindingStub        func(bindingID string, deploymentTopology bosh.BoshVMs, manifest []byte, requestParams map[string]interface{}, logger *log.Logger) error
	deleteBindingMutex       sync.RWMutex
	deleteBindingArgsForCall []struct {
		bindingID          string
		deploymentTopology bosh.BoshVMs
		manifest           []byte
		requestParams      map[string]interface{}
		logger             *log.Logger
	}
	deleteBindingReturns struct {
		result1 error
	}
	deleteBindingReturnsOnCall map[int]struct {
		result1 error
	}
	GenerateDashboardUrlStub        func(instanceID string, plan serviceadapter.Plan, manifest []byte, logger *log.Logger) (string, error)
	generateDashboardUrlMutex       sync.RWMutex
	generateDashboardUrlArgsForCall []struct {
		instanceID string
		plan       serviceadapter.Plan
		manifest   []byte
		logger     *log.Logger
	}
	generateDashboardUrlReturns struct {
		result1 string
		result2 error
	}
	generateDashboardUrlReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GeneratePlanSchemaStub        func(plan serviceadapter.Plan, logger *log.Logger) (brokerapi.ServiceSchemas, error)
	generatePlanSchemaMutex       sync.RWMutex
	generatePlanSchemaArgsForCall []struct {
		plan   serviceadapter.Plan
		logger *log.Logger
	}
	generatePlanSchemaReturns struct {
		result1 brokerapi.ServiceSchemas
		result2 error
	}
	generatePlanSchemaReturnsOnCall map[int]struct {
		result1 brokerapi.ServiceSchemas
		result2 error
	}
	GenerateManifestStub        func(deploymentName, planID string, requestParams map[string]interface{}, oldManifest []byte, previousPlanID *string, logger *log.Logger) (serviceadapter.MarshalledGenerateManifest, error)
	generateManifestMutex       sync.RWMutex
	generateManifestArgsForCall []struct {
		deploymentName string
		planID         string
		requestParams  map[string]interface{}
		oldManifest    []byte
		previousPlanID *string
		logger         *log.Logger
	}
	generateManifestReturns struct {
		result1 serviceadapter.MarshalledGenerateManifest
		result2 error
	}
	generateManifestReturnsOnCall map[int]struct {
		result1 serviceadapter.MarshalledGenerateManifest
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceAdapterClient) CreateBinding(bindingID string, deploymentTopology bosh.BoshVMs, manifest []byte, requestParams map[string]interface{}, secretsMap map[string]string, logger *log.Logger) (serviceadapter.Binding, error) {
	var manifestCopy []byte
	if manifest != nil {
		manifestCopy = make([]byte, len(manifest))
		copy(manifestCopy, manifest)
	}
	fake.createBindingMutex.Lock()
	ret, specificReturn := fake.createBindingReturnsOnCall[len(fake.createBindingArgsForCall)]
	fake.createBindingArgsForCall = append(fake.createBindingArgsForCall, struct {
		bindingID          string
		deploymentTopology bosh.BoshVMs
		manifest           []byte
		requestParams      map[string]interface{}
		secretsMap         map[string]string
		logger             *log.Logger
	}{bindingID, deploymentTopology, manifestCopy, requestParams, secretsMap, logger})
	fake.recordInvocation("CreateBinding", []interface{}{bindingID, deploymentTopology, manifestCopy, requestParams, secretsMap, logger})
	fake.createBindingMutex.Unlock()
	if fake.CreateBindingStub != nil {
		return fake.CreateBindingStub(bindingID, deploymentTopology, manifest, requestParams, secretsMap, logger)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createBindingReturns.result1, fake.createBindingReturns.result2
}

func (fake *FakeServiceAdapterClient) CreateBindingCallCount() int {
	fake.createBindingMutex.RLock()
	defer fake.createBindingMutex.RUnlock()
	return len(fake.createBindingArgsForCall)
}

func (fake *FakeServiceAdapterClient) CreateBindingArgsForCall(i int) (string, bosh.BoshVMs, []byte, map[string]interface{}, map[string]string, *log.Logger) {
	fake.createBindingMutex.RLock()
	defer fake.createBindingMutex.RUnlock()
	return fake.createBindingArgsForCall[i].bindingID, fake.createBindingArgsForCall[i].deploymentTopology, fake.createBindingArgsForCall[i].manifest, fake.createBindingArgsForCall[i].requestParams, fake.createBindingArgsForCall[i].secretsMap, fake.createBindingArgsForCall[i].logger
}

func (fake *FakeServiceAdapterClient) CreateBindingReturns(result1 serviceadapter.Binding, result2 error) {
	fake.CreateBindingStub = nil
	fake.createBindingReturns = struct {
		result1 serviceadapter.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceAdapterClient) CreateBindingReturnsOnCall(i int, result1 serviceadapter.Binding, result2 error) {
	fake.CreateBindingStub = nil
	if fake.createBindingReturnsOnCall == nil {
		fake.createBindingReturnsOnCall = make(map[int]struct {
			result1 serviceadapter.Binding
			result2 error
		})
	}
	fake.createBindingReturnsOnCall[i] = struct {
		result1 serviceadapter.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceAdapterClient) DeleteBinding(bindingID string, deploymentTopology bosh.BoshVMs, manifest []byte, requestParams map[string]interface{}, logger *log.Logger) error {
	var manifestCopy []byte
	if manifest != nil {
		manifestCopy = make([]byte, len(manifest))
		copy(manifestCopy, manifest)
	}
	fake.deleteBindingMutex.Lock()
	ret, specificReturn := fake.deleteBindingReturnsOnCall[len(fake.deleteBindingArgsForCall)]
	fake.deleteBindingArgsForCall = append(fake.deleteBindingArgsForCall, struct {
		bindingID          string
		deploymentTopology bosh.BoshVMs
		manifest           []byte
		requestParams      map[string]interface{}
		logger             *log.Logger
	}{bindingID, deploymentTopology, manifestCopy, requestParams, logger})
	fake.recordInvocation("DeleteBinding", []interface{}{bindingID, deploymentTopology, manifestCopy, requestParams, logger})
	fake.deleteBindingMutex.Unlock()
	if fake.DeleteBindingStub != nil {
		return fake.DeleteBindingStub(bindingID, deploymentTopology, manifest, requestParams, logger)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.deleteBindingReturns.result1
}

func (fake *FakeServiceAdapterClient) DeleteBindingCallCount() int {
	fake.deleteBindingMutex.RLock()
	defer fake.deleteBindingMutex.RUnlock()
	return len(fake.deleteBindingArgsForCall)
}

func (fake *FakeServiceAdapterClient) DeleteBindingArgsForCall(i int) (string, bosh.BoshVMs, []byte, map[string]interface{}, *log.Logger) {
	fake.deleteBindingMutex.RLock()
	defer fake.deleteBindingMutex.RUnlock()
	return fake.deleteBindingArgsForCall[i].bindingID, fake.deleteBindingArgsForCall[i].deploymentTopology, fake.deleteBindingArgsForCall[i].manifest, fake.deleteBindingArgsForCall[i].requestParams, fake.deleteBindingArgsForCall[i].logger
}

func (fake *FakeServiceAdapterClient) DeleteBindingReturns(result1 error) {
	fake.DeleteBindingStub = nil
	fake.deleteBindingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAdapterClient) DeleteBindingReturnsOnCall(i int, result1 error) {
	fake.DeleteBindingStub = nil
	if fake.deleteBindingReturnsOnCall == nil {
		fake.deleteBindingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteBindingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceAdapterClient) GenerateDashboardUrl(instanceID string, plan serviceadapter.Plan, manifest []byte, logger *log.Logger) (string, error) {
	var manifestCopy []byte
	if manifest != nil {
		manifestCopy = make([]byte, len(manifest))
		copy(manifestCopy, manifest)
	}
	fake.generateDashboardUrlMutex.Lock()
	ret, specificReturn := fake.generateDashboardUrlReturnsOnCall[len(fake.generateDashboardUrlArgsForCall)]
	fake.generateDashboardUrlArgsForCall = append(fake.generateDashboardUrlArgsForCall, struct {
		instanceID string
		plan       serviceadapter.Plan
		manifest   []byte
		logger     *log.Logger
	}{instanceID, plan, manifestCopy, logger})
	fake.recordInvocation("GenerateDashboardUrl", []interface{}{instanceID, plan, manifestCopy, logger})
	fake.generateDashboardUrlMutex.Unlock()
	if fake.GenerateDashboardUrlStub != nil {
		return fake.GenerateDashboardUrlStub(instanceID, plan, manifest, logger)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.generateDashboardUrlReturns.result1, fake.generateDashboardUrlReturns.result2
}

func (fake *FakeServiceAdapterClient) GenerateDashboardUrlCallCount() int {
	fake.generateDashboardUrlMutex.RLock()
	defer fake.generateDashboardUrlMutex.RUnlock()
	return len(fake.generateDashboardUrlArgsForCall)
}

func (fake *FakeServiceAdapterClient) GenerateDashboardUrlArgsForCall(i int) (string, serviceadapter.Plan, []byte, *log.Logger) {
	fake.generateDashboardUrlMutex.RLock()
	defer fake.generateDashboardUrlMutex.RUnlock()
	return fake.generateDashboardUrlArgsForCall[i].instanceID, fake.generateDashboardUrlArgsForCall[i].plan, fake.generateDashboardUrlArgsForCall[i].manifest, fake.generateDashboardUrlArgsForCall[i].logger
}

func (fake *FakeServiceAdapterClient) GenerateDashboardUrlReturns(result1 string, result2 error) {
	fake.GenerateDashboardUrlStub = nil
	fake.generateDashboardUrlReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceAdapterClient) GenerateDashboardUrlReturnsOnCall(i int, result1 string, result2 error) {
	fake.GenerateDashboardUrlStub = nil
	if fake.generateDashboardUrlReturnsOnCall == nil {
		fake.generateDashboardUrlReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.generateDashboardUrlReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceAdapterClient) GeneratePlanSchema(plan serviceadapter.Plan, logger *log.Logger) (brokerapi.ServiceSchemas, error) {
	fake.generatePlanSchemaMutex.Lock()
	ret, specificReturn := fake.generatePlanSchemaReturnsOnCall[len(fake.generatePlanSchemaArgsForCall)]
	fake.generatePlanSchemaArgsForCall = append(fake.generatePlanSchemaArgsForCall, struct {
		plan   serviceadapter.Plan
		logger *log.Logger
	}{plan, logger})
	fake.recordInvocation("GeneratePlanSchema", []interface{}{plan, logger})
	fake.generatePlanSchemaMutex.Unlock()
	if fake.GeneratePlanSchemaStub != nil {
		return fake.GeneratePlanSchemaStub(plan, logger)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.generatePlanSchemaReturns.result1, fake.generatePlanSchemaReturns.result2
}

func (fake *FakeServiceAdapterClient) GeneratePlanSchemaCallCount() int {
	fake.generatePlanSchemaMutex.RLock()
	defer fake.generatePlanSchemaMutex.RUnlock()
	return len(fake.generatePlanSchemaArgsForCall)
}

func (fake *FakeServiceAdapterClient) GeneratePlanSchemaArgsForCall(i int) (serviceadapter.Plan, *log.Logger) {
	fake.generatePlanSchemaMutex.RLock()
	defer fake.generatePlanSchemaMutex.RUnlock()
	return fake.generatePlanSchemaArgsForCall[i].plan, fake.generatePlanSchemaArgsForCall[i].logger
}

func (fake *FakeServiceAdapterClient) GeneratePlanSchemaReturns(result1 brokerapi.ServiceSchemas, result2 error) {
	fake.GeneratePlanSchemaStub = nil
	fake.generatePlanSchemaReturns = struct {
		result1 brokerapi.ServiceSchemas
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceAdapterClient) GeneratePlanSchemaReturnsOnCall(i int, result1 brokerapi.ServiceSchemas, result2 error) {
	fake.GeneratePlanSchemaStub = nil
	if fake.generatePlanSchemaReturnsOnCall == nil {
		fake.generatePlanSchemaReturnsOnCall = make(map[int]struct {
			result1 brokerapi.ServiceSchemas
			result2 error
		})
	}
	fake.generatePlanSchemaReturnsOnCall[i] = struct {
		result1 brokerapi.ServiceSchemas
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceAdapterClient) GenerateManifest(deploymentName string, planID string, requestParams map[string]interface{}, oldManifest []byte, previousPlanID *string, logger *log.Logger) (serviceadapter.MarshalledGenerateManifest, error) {
	var oldManifestCopy []byte
	if oldManifest != nil {
		oldManifestCopy = make([]byte, len(oldManifest))
		copy(oldManifestCopy, oldManifest)
	}
	fake.generateManifestMutex.Lock()
	ret, specificReturn := fake.generateManifestReturnsOnCall[len(fake.generateManifestArgsForCall)]
	fake.generateManifestArgsForCall = append(fake.generateManifestArgsForCall, struct {
		deploymentName string
		planID         string
		requestParams  map[string]interface{}
		oldManifest    []byte
		previousPlanID *string
		logger         *log.Logger
	}{deploymentName, planID, requestParams, oldManifestCopy, previousPlanID, logger})
	fake.recordInvocation("GenerateManifest", []interface{}{deploymentName, planID, requestParams, oldManifestCopy, previousPlanID, logger})
	fake.generateManifestMutex.Unlock()
	if fake.GenerateManifestStub != nil {
		return fake.GenerateManifestStub(deploymentName, planID, requestParams, oldManifest, previousPlanID, logger)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.generateManifestReturns.result1, fake.generateManifestReturns.result2
}

func (fake *FakeServiceAdapterClient) GenerateManifestCallCount() int {
	fake.generateManifestMutex.RLock()
	defer fake.generateManifestMutex.RUnlock()
	return len(fake.generateManifestArgsForCall)
}

func (fake *FakeServiceAdapterClient) GenerateManifestArgsForCall(i int) (string, string, map[string]interface{}, []byte, *string, *log.Logger) {
	fake.generateManifestMutex.RLock()
	defer fake.generateManifestMutex.RUnlock()
	return fake.generateManifestArgsForCall[i].deploymentName, fake.generateManifestArgsForCall[i].planID, fake.generateManifestArgsForCall[i].requestParams, fake.generateManifestArgsForCall[i].oldManifest, fake.generateManifestArgsForCall[i].previousPlanID, fake.generateManifestArgsForCall[i].logger
}

func (fake *FakeServiceAdapterClient) GenerateManifestReturns(result1 serviceadapter.MarshalledGenerateManifest, result2 error) {
	fake.GenerateManifestStub = nil
	fake.generateManifestReturns = struct {
		result1 serviceadapter.MarshalledGenerateManifest
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceAdapterClient) GenerateManifestReturnsOnCall(i int, result1 serviceadapter.MarshalledGenerateManifest, result2 error) {
	fake.GenerateManifestStub = nil
	if fake.generateManifestReturnsOnCall == nil {
		fake.generateManifestReturnsOnCall = make(map[int]struct {
			result1 serviceadapter.MarshalledGenerateManifest
			result2 error
		})
	}
	fake.generateManifestReturnsOnCall[i] = struct {
		result1 serviceadapter.MarshalledGenerateManifest
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceAdapterClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createBindingMutex.RLock()
	defer fake.createBindingMutex.RUnlock()
	fake.deleteBindingMutex.RLock()
	defer fake.deleteBindingMutex.RUnlock()
	fake.generateDashboardUrlMutex.RLock()
	defer fake.generateDashboardUrlMutex.RUnlock()
	fake.generatePlanSchemaMutex.RLock()
	defer fake.generatePlanSchemaMutex.RUnlock()
	fake.generateManifestMutex.RLock()
	defer fake.generateManifestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceAdapterClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ broker.ServiceAdapterClient = new(FakeServiceAdapterClient)
