// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/pivotal-cf/on-demand-service-broker/instanceiterator"
	"github.com/pivotal-cf/on-demand-service-broker/service"
)

type FakeInstanceLister struct {
	InstancesStub        func() ([]service.Instance, error)
	instancesMutex       sync.RWMutex
	instancesArgsForCall []struct{}
	instancesReturns     struct {
		result1 []service.Instance
		result2 error
	}
	instancesReturnsOnCall map[int]struct {
		result1 []service.Instance
		result2 error
	}
	FilteredInstancesStub        func(filter map[string]string) ([]service.Instance, error)
	filteredInstancesMutex       sync.RWMutex
	filteredInstancesArgsForCall []struct {
		filter map[string]string
	}
	filteredInstancesReturns struct {
		result1 []service.Instance
		result2 error
	}
	filteredInstancesReturnsOnCall map[int]struct {
		result1 []service.Instance
		result2 error
	}
	LatestInstanceInfoStub        func(inst service.Instance) (service.Instance, error)
	latestInstanceInfoMutex       sync.RWMutex
	latestInstanceInfoArgsForCall []struct {
		inst service.Instance
	}
	latestInstanceInfoReturns struct {
		result1 service.Instance
		result2 error
	}
	latestInstanceInfoReturnsOnCall map[int]struct {
		result1 service.Instance
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInstanceLister) Instances() ([]service.Instance, error) {
	fake.instancesMutex.Lock()
	ret, specificReturn := fake.instancesReturnsOnCall[len(fake.instancesArgsForCall)]
	fake.instancesArgsForCall = append(fake.instancesArgsForCall, struct{}{})
	fake.recordInvocation("Instances", []interface{}{})
	fake.instancesMutex.Unlock()
	if fake.InstancesStub != nil {
		return fake.InstancesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.instancesReturns.result1, fake.instancesReturns.result2
}

func (fake *FakeInstanceLister) InstancesCallCount() int {
	fake.instancesMutex.RLock()
	defer fake.instancesMutex.RUnlock()
	return len(fake.instancesArgsForCall)
}

func (fake *FakeInstanceLister) InstancesReturns(result1 []service.Instance, result2 error) {
	fake.InstancesStub = nil
	fake.instancesReturns = struct {
		result1 []service.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceLister) InstancesReturnsOnCall(i int, result1 []service.Instance, result2 error) {
	fake.InstancesStub = nil
	if fake.instancesReturnsOnCall == nil {
		fake.instancesReturnsOnCall = make(map[int]struct {
			result1 []service.Instance
			result2 error
		})
	}
	fake.instancesReturnsOnCall[i] = struct {
		result1 []service.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceLister) FilteredInstances(filter map[string]string) ([]service.Instance, error) {
	fake.filteredInstancesMutex.Lock()
	ret, specificReturn := fake.filteredInstancesReturnsOnCall[len(fake.filteredInstancesArgsForCall)]
	fake.filteredInstancesArgsForCall = append(fake.filteredInstancesArgsForCall, struct {
		filter map[string]string
	}{filter})
	fake.recordInvocation("FilteredInstances", []interface{}{filter})
	fake.filteredInstancesMutex.Unlock()
	if fake.FilteredInstancesStub != nil {
		return fake.FilteredInstancesStub(filter)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.filteredInstancesReturns.result1, fake.filteredInstancesReturns.result2
}

func (fake *FakeInstanceLister) FilteredInstancesCallCount() int {
	fake.filteredInstancesMutex.RLock()
	defer fake.filteredInstancesMutex.RUnlock()
	return len(fake.filteredInstancesArgsForCall)
}

func (fake *FakeInstanceLister) FilteredInstancesArgsForCall(i int) map[string]string {
	fake.filteredInstancesMutex.RLock()
	defer fake.filteredInstancesMutex.RUnlock()
	return fake.filteredInstancesArgsForCall[i].filter
}

func (fake *FakeInstanceLister) FilteredInstancesReturns(result1 []service.Instance, result2 error) {
	fake.FilteredInstancesStub = nil
	fake.filteredInstancesReturns = struct {
		result1 []service.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceLister) FilteredInstancesReturnsOnCall(i int, result1 []service.Instance, result2 error) {
	fake.FilteredInstancesStub = nil
	if fake.filteredInstancesReturnsOnCall == nil {
		fake.filteredInstancesReturnsOnCall = make(map[int]struct {
			result1 []service.Instance
			result2 error
		})
	}
	fake.filteredInstancesReturnsOnCall[i] = struct {
		result1 []service.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceLister) LatestInstanceInfo(inst service.Instance) (service.Instance, error) {
	fake.latestInstanceInfoMutex.Lock()
	ret, specificReturn := fake.latestInstanceInfoReturnsOnCall[len(fake.latestInstanceInfoArgsForCall)]
	fake.latestInstanceInfoArgsForCall = append(fake.latestInstanceInfoArgsForCall, struct {
		inst service.Instance
	}{inst})
	fake.recordInvocation("LatestInstanceInfo", []interface{}{inst})
	fake.latestInstanceInfoMutex.Unlock()
	if fake.LatestInstanceInfoStub != nil {
		return fake.LatestInstanceInfoStub(inst)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.latestInstanceInfoReturns.result1, fake.latestInstanceInfoReturns.result2
}

func (fake *FakeInstanceLister) LatestInstanceInfoCallCount() int {
	fake.latestInstanceInfoMutex.RLock()
	defer fake.latestInstanceInfoMutex.RUnlock()
	return len(fake.latestInstanceInfoArgsForCall)
}

func (fake *FakeInstanceLister) LatestInstanceInfoArgsForCall(i int) service.Instance {
	fake.latestInstanceInfoMutex.RLock()
	defer fake.latestInstanceInfoMutex.RUnlock()
	return fake.latestInstanceInfoArgsForCall[i].inst
}

func (fake *FakeInstanceLister) LatestInstanceInfoReturns(result1 service.Instance, result2 error) {
	fake.LatestInstanceInfoStub = nil
	fake.latestInstanceInfoReturns = struct {
		result1 service.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceLister) LatestInstanceInfoReturnsOnCall(i int, result1 service.Instance, result2 error) {
	fake.LatestInstanceInfoStub = nil
	if fake.latestInstanceInfoReturnsOnCall == nil {
		fake.latestInstanceInfoReturnsOnCall = make(map[int]struct {
			result1 service.Instance
			result2 error
		})
	}
	fake.latestInstanceInfoReturnsOnCall[i] = struct {
		result1 service.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceLister) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.instancesMutex.RLock()
	defer fake.instancesMutex.RUnlock()
	fake.filteredInstancesMutex.RLock()
	defer fake.filteredInstancesMutex.RUnlock()
	fake.latestInstanceInfoMutex.RLock()
	defer fake.latestInstanceInfoMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInstanceLister) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ instanceiterator.InstanceLister = new(FakeInstanceLister)
