#!/usr/bin/env bash

if [[ -z "${BOSH_LITE_NAME:-""}" ]]; then
    echo "BOSH_LITE_NAME not set. Did you run target-lite?"
    exit 1
fi

env_name="$BOSH_LITE_NAME"
$META/concourse/bosh-lites-pool/tasks/make-broker-deployment-vars.sh "${env_name}" > /tmp/broker-${env_name}.yml

export GOPATH="$ODB"
export BOSH_DEPLOYMENT_VARS="/tmp/broker-${env_name}.yml"
export BROKER_SYSTEM_DOMAIN="$BOSH_LITE_DOMAIN"
export EXAMPLE_SI_API_PATH=~/workspace/example-service-instances-api
export KAFKA_EXAMPLE_APP_PATH=~/workspace/kafka-example-app
export KAFKA_SERVICE_ADAPTER_RELEASE_NAME=kafka-example-service-adapter
export KAFKA_SERVICE_RELEASE_NAME=kafka-example-service
export ODB_RELEASE_TEMPLATES_PATH=~/workspace/on-demand-service-broker-release/examples/deployment
export ODB_VERSION=latest
export REDIS_EXAMPLE_APP_PATH=~/workspace/cf-redis-example-app
export REDIS_SERVICE_ADAPTER_RELEASE_NAME=redis-example-service-adapter
export REDIS_SERVICE_RELEASE_NAME=redis-example-service
export SI_API_PATH="$HOME/workspace/example-service-instances-api/"

export BOSH_CA_CERT="$BOSH_CA_CERT"
export BOSH_CLIENT="$BOSH_CLIENT"
export BOSH_CLIENT_SECRET="$BOSH_CLIENT_SECRET"
export BOSH_ENVIRONMENT="$BOSH_ENVIRONMENT"
export BOSH_GW_USER="$BOSH_GW_USER"
export BOSH_GW_HOST="$BOSH_GW_HOST"
export BOSH_GW_PRIVATE_KEY_CONTENTS="$BOSH_GW_PRIVATE_KEY_CONTENTS"
export BOSH_LITE_DOMAIN="$BOSH_LITE_DOMAIN"
export CREDHUB_SERVER="$CREDHUB_SERVER"
export CREDHUB_CLIENT="$CREDHUB_CLIENT"
export CREDHUB_SECRET="$CREDHUB_SECRET"
export CREDHUB_CA_CERT="$CREDHUB_CA_CERT"
export CF_API="$CF_API"
export CF_PASSWORD="$CF_PASSWORD"
export CF_USERNAME="$CF_USERNAME"
export CF_ORG="$CF_ORG"
export CF_SPACE="$CF_SPACE"

echo -e "$BOSH_GW_PRIVATE_KEY_CONTENTS" > /tmp/jb-$env_name.pem
chmod 700 /tmp/jb-$env_name.pem
export BOSH_GW_PRIVATE_KEY=/tmp/jb-$env_name.pem

export BOSH_NON_INTERACTIVE=true

export CF_URL="$(bosh int --path /cf/api_url "$BOSH_DEPLOYMENT_VARS")"
export CF_UAA_URL="https://uaa.$BOSH_LITE_DOMAIN"
export CF_CLIENT_ID="$(bosh int --path /cf/client_credentials/client_id "$BOSH_DEPLOYMENT_VARS" 2>/dev/null)"
export CF_CLIENT_SECRET="$(bosh int --path /cf/client_credentials/client_secret "$BOSH_DEPLOYMENT_VARS" 2>/dev/null)"
export CF_USERNAME="$(bosh int --path /cf/user_credentials/username "$BOSH_DEPLOYMENT_VARS" 2>/dev/null)"
export CF_PASSWORD="$(bosh int --path /cf/user_credentials/password "$BOSH_DEPLOYMENT_VARS" 2>/dev/null)"
export CF_ORG="$(bosh int --path /cf/org "$BOSH_DEPLOYMENT_VARS")"
export CF_SPACE="$(bosh int --path /cf/space "$BOSH_DEPLOYMENT_VARS")"
export DOPPLER_ADDRESS=wss://doppler.${BOSH_LITE_DOMAIN}

export PREVIOUS_ADAPTER_RELEASE_URL="https://storage.googleapis.com/dev-releases/redis-example-service-adapter-prev-0.28.0.tgz" # TODO: fix this
export PREVIOUS_ODB_RELEASE_URL="https://storage.googleapis.com/dev-releases/on-demand-service-broker-prev-0.28.0.tgz"
export PREVIOUS_ADAPTER_VERSION="0.28.0"
export PREVIOUS_ODB_VERSION="0.28.0"
export PREVIOUS_ODB_RELEASE_NAME="on-demand-service-broker-prev"
export PREVIOUS_ADAPTER_RELEASE_NAME="redis-example-service-adapter-prev"

cf api ${CF_URL} --skip-ssl-validation
if [[ -n "${CF_CLIENT_ID:-""}" && "${CF_CLIENT_ID:-""}" != "null" ]]; then
  cf auth "$CF_CLIENT_ID" "$CF_CLIENT_SECRET" --client-credentials
else
  cf auth $CF_USERNAME $CF_PASSWORD
fi
cf target -o ${CF_ORG} -s ${CF_SPACE} # must already exist
