// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"log"
	"sync"

	"github.com/pivotal-cf/on-demand-service-broker/cf"
	"github.com/pivotal-cf/on-demand-service-broker/deleter"
	"github.com/pivotal-cf/on-demand-service-broker/service"
)

type FakeCloudFoundryClient struct {
	DeleteBindingStub        func(cf.Binding, *log.Logger) error
	deleteBindingMutex       sync.RWMutex
	deleteBindingArgsForCall []struct {
		arg1 cf.Binding
		arg2 *log.Logger
	}
	deleteBindingReturns struct {
		result1 error
	}
	deleteBindingReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteServiceInstanceStub        func(string, *log.Logger) error
	deleteServiceInstanceMutex       sync.RWMutex
	deleteServiceInstanceArgsForCall []struct {
		arg1 string
		arg2 *log.Logger
	}
	deleteServiceInstanceReturns struct {
		result1 error
	}
	deleteServiceInstanceReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteServiceKeyStub        func(cf.ServiceKey, *log.Logger) error
	deleteServiceKeyMutex       sync.RWMutex
	deleteServiceKeyArgsForCall []struct {
		arg1 cf.ServiceKey
		arg2 *log.Logger
	}
	deleteServiceKeyReturns struct {
		result1 error
	}
	deleteServiceKeyReturnsOnCall map[int]struct {
		result1 error
	}
	GetBindingsForInstanceStub        func(string, *log.Logger) ([]cf.Binding, error)
	getBindingsForInstanceMutex       sync.RWMutex
	getBindingsForInstanceArgsForCall []struct {
		arg1 string
		arg2 *log.Logger
	}
	getBindingsForInstanceReturns struct {
		result1 []cf.Binding
		result2 error
	}
	getBindingsForInstanceReturnsOnCall map[int]struct {
		result1 []cf.Binding
		result2 error
	}
	GetInstanceStub        func(string, *log.Logger) (cf.Instance, error)
	getInstanceMutex       sync.RWMutex
	getInstanceArgsForCall []struct {
		arg1 string
		arg2 *log.Logger
	}
	getInstanceReturns struct {
		result1 cf.Instance
		result2 error
	}
	getInstanceReturnsOnCall map[int]struct {
		result1 cf.Instance
		result2 error
	}
	GetInstancesOfServiceOfferingStub        func(string, *log.Logger) ([]service.Instance, error)
	getInstancesOfServiceOfferingMutex       sync.RWMutex
	getInstancesOfServiceOfferingArgsForCall []struct {
		arg1 string
		arg2 *log.Logger
	}
	getInstancesOfServiceOfferingReturns struct {
		result1 []service.Instance
		result2 error
	}
	getInstancesOfServiceOfferingReturnsOnCall map[int]struct {
		result1 []service.Instance
		result2 error
	}
	GetServiceKeysForInstanceStub        func(string, *log.Logger) ([]cf.ServiceKey, error)
	getServiceKeysForInstanceMutex       sync.RWMutex
	getServiceKeysForInstanceArgsForCall []struct {
		arg1 string
		arg2 *log.Logger
	}
	getServiceKeysForInstanceReturns struct {
		result1 []cf.ServiceKey
		result2 error
	}
	getServiceKeysForInstanceReturnsOnCall map[int]struct {
		result1 []cf.ServiceKey
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCloudFoundryClient) DeleteBinding(arg1 cf.Binding, arg2 *log.Logger) error {
	fake.deleteBindingMutex.Lock()
	ret, specificReturn := fake.deleteBindingReturnsOnCall[len(fake.deleteBindingArgsForCall)]
	fake.deleteBindingArgsForCall = append(fake.deleteBindingArgsForCall, struct {
		arg1 cf.Binding
		arg2 *log.Logger
	}{arg1, arg2})
	fake.recordInvocation("DeleteBinding", []interface{}{arg1, arg2})
	fake.deleteBindingMutex.Unlock()
	if fake.DeleteBindingStub != nil {
		return fake.DeleteBindingStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteBindingReturns
	return fakeReturns.result1
}

func (fake *FakeCloudFoundryClient) DeleteBindingCallCount() int {
	fake.deleteBindingMutex.RLock()
	defer fake.deleteBindingMutex.RUnlock()
	return len(fake.deleteBindingArgsForCall)
}

func (fake *FakeCloudFoundryClient) DeleteBindingCalls(stub func(cf.Binding, *log.Logger) error) {
	fake.deleteBindingMutex.Lock()
	defer fake.deleteBindingMutex.Unlock()
	fake.DeleteBindingStub = stub
}

func (fake *FakeCloudFoundryClient) DeleteBindingArgsForCall(i int) (cf.Binding, *log.Logger) {
	fake.deleteBindingMutex.RLock()
	defer fake.deleteBindingMutex.RUnlock()
	argsForCall := fake.deleteBindingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudFoundryClient) DeleteBindingReturns(result1 error) {
	fake.deleteBindingMutex.Lock()
	defer fake.deleteBindingMutex.Unlock()
	fake.DeleteBindingStub = nil
	fake.deleteBindingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudFoundryClient) DeleteBindingReturnsOnCall(i int, result1 error) {
	fake.deleteBindingMutex.Lock()
	defer fake.deleteBindingMutex.Unlock()
	fake.DeleteBindingStub = nil
	if fake.deleteBindingReturnsOnCall == nil {
		fake.deleteBindingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteBindingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudFoundryClient) DeleteServiceInstance(arg1 string, arg2 *log.Logger) error {
	fake.deleteServiceInstanceMutex.Lock()
	ret, specificReturn := fake.deleteServiceInstanceReturnsOnCall[len(fake.deleteServiceInstanceArgsForCall)]
	fake.deleteServiceInstanceArgsForCall = append(fake.deleteServiceInstanceArgsForCall, struct {
		arg1 string
		arg2 *log.Logger
	}{arg1, arg2})
	fake.recordInvocation("DeleteServiceInstance", []interface{}{arg1, arg2})
	fake.deleteServiceInstanceMutex.Unlock()
	if fake.DeleteServiceInstanceStub != nil {
		return fake.DeleteServiceInstanceStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteServiceInstanceReturns
	return fakeReturns.result1
}

func (fake *FakeCloudFoundryClient) DeleteServiceInstanceCallCount() int {
	fake.deleteServiceInstanceMutex.RLock()
	defer fake.deleteServiceInstanceMutex.RUnlock()
	return len(fake.deleteServiceInstanceArgsForCall)
}

func (fake *FakeCloudFoundryClient) DeleteServiceInstanceCalls(stub func(string, *log.Logger) error) {
	fake.deleteServiceInstanceMutex.Lock()
	defer fake.deleteServiceInstanceMutex.Unlock()
	fake.DeleteServiceInstanceStub = stub
}

func (fake *FakeCloudFoundryClient) DeleteServiceInstanceArgsForCall(i int) (string, *log.Logger) {
	fake.deleteServiceInstanceMutex.RLock()
	defer fake.deleteServiceInstanceMutex.RUnlock()
	argsForCall := fake.deleteServiceInstanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudFoundryClient) DeleteServiceInstanceReturns(result1 error) {
	fake.deleteServiceInstanceMutex.Lock()
	defer fake.deleteServiceInstanceMutex.Unlock()
	fake.DeleteServiceInstanceStub = nil
	fake.deleteServiceInstanceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudFoundryClient) DeleteServiceInstanceReturnsOnCall(i int, result1 error) {
	fake.deleteServiceInstanceMutex.Lock()
	defer fake.deleteServiceInstanceMutex.Unlock()
	fake.DeleteServiceInstanceStub = nil
	if fake.deleteServiceInstanceReturnsOnCall == nil {
		fake.deleteServiceInstanceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteServiceInstanceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudFoundryClient) DeleteServiceKey(arg1 cf.ServiceKey, arg2 *log.Logger) error {
	fake.deleteServiceKeyMutex.Lock()
	ret, specificReturn := fake.deleteServiceKeyReturnsOnCall[len(fake.deleteServiceKeyArgsForCall)]
	fake.deleteServiceKeyArgsForCall = append(fake.deleteServiceKeyArgsForCall, struct {
		arg1 cf.ServiceKey
		arg2 *log.Logger
	}{arg1, arg2})
	fake.recordInvocation("DeleteServiceKey", []interface{}{arg1, arg2})
	fake.deleteServiceKeyMutex.Unlock()
	if fake.DeleteServiceKeyStub != nil {
		return fake.DeleteServiceKeyStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteServiceKeyReturns
	return fakeReturns.result1
}

func (fake *FakeCloudFoundryClient) DeleteServiceKeyCallCount() int {
	fake.deleteServiceKeyMutex.RLock()
	defer fake.deleteServiceKeyMutex.RUnlock()
	return len(fake.deleteServiceKeyArgsForCall)
}

func (fake *FakeCloudFoundryClient) DeleteServiceKeyCalls(stub func(cf.ServiceKey, *log.Logger) error) {
	fake.deleteServiceKeyMutex.Lock()
	defer fake.deleteServiceKeyMutex.Unlock()
	fake.DeleteServiceKeyStub = stub
}

func (fake *FakeCloudFoundryClient) DeleteServiceKeyArgsForCall(i int) (cf.ServiceKey, *log.Logger) {
	fake.deleteServiceKeyMutex.RLock()
	defer fake.deleteServiceKeyMutex.RUnlock()
	argsForCall := fake.deleteServiceKeyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudFoundryClient) DeleteServiceKeyReturns(result1 error) {
	fake.deleteServiceKeyMutex.Lock()
	defer fake.deleteServiceKeyMutex.Unlock()
	fake.DeleteServiceKeyStub = nil
	fake.deleteServiceKeyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudFoundryClient) DeleteServiceKeyReturnsOnCall(i int, result1 error) {
	fake.deleteServiceKeyMutex.Lock()
	defer fake.deleteServiceKeyMutex.Unlock()
	fake.DeleteServiceKeyStub = nil
	if fake.deleteServiceKeyReturnsOnCall == nil {
		fake.deleteServiceKeyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteServiceKeyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudFoundryClient) GetBindingsForInstance(arg1 string, arg2 *log.Logger) ([]cf.Binding, error) {
	fake.getBindingsForInstanceMutex.Lock()
	ret, specificReturn := fake.getBindingsForInstanceReturnsOnCall[len(fake.getBindingsForInstanceArgsForCall)]
	fake.getBindingsForInstanceArgsForCall = append(fake.getBindingsForInstanceArgsForCall, struct {
		arg1 string
		arg2 *log.Logger
	}{arg1, arg2})
	fake.recordInvocation("GetBindingsForInstance", []interface{}{arg1, arg2})
	fake.getBindingsForInstanceMutex.Unlock()
	if fake.GetBindingsForInstanceStub != nil {
		return fake.GetBindingsForInstanceStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getBindingsForInstanceReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCloudFoundryClient) GetBindingsForInstanceCallCount() int {
	fake.getBindingsForInstanceMutex.RLock()
	defer fake.getBindingsForInstanceMutex.RUnlock()
	return len(fake.getBindingsForInstanceArgsForCall)
}

func (fake *FakeCloudFoundryClient) GetBindingsForInstanceCalls(stub func(string, *log.Logger) ([]cf.Binding, error)) {
	fake.getBindingsForInstanceMutex.Lock()
	defer fake.getBindingsForInstanceMutex.Unlock()
	fake.GetBindingsForInstanceStub = stub
}

func (fake *FakeCloudFoundryClient) GetBindingsForInstanceArgsForCall(i int) (string, *log.Logger) {
	fake.getBindingsForInstanceMutex.RLock()
	defer fake.getBindingsForInstanceMutex.RUnlock()
	argsForCall := fake.getBindingsForInstanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudFoundryClient) GetBindingsForInstanceReturns(result1 []cf.Binding, result2 error) {
	fake.getBindingsForInstanceMutex.Lock()
	defer fake.getBindingsForInstanceMutex.Unlock()
	fake.GetBindingsForInstanceStub = nil
	fake.getBindingsForInstanceReturns = struct {
		result1 []cf.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudFoundryClient) GetBindingsForInstanceReturnsOnCall(i int, result1 []cf.Binding, result2 error) {
	fake.getBindingsForInstanceMutex.Lock()
	defer fake.getBindingsForInstanceMutex.Unlock()
	fake.GetBindingsForInstanceStub = nil
	if fake.getBindingsForInstanceReturnsOnCall == nil {
		fake.getBindingsForInstanceReturnsOnCall = make(map[int]struct {
			result1 []cf.Binding
			result2 error
		})
	}
	fake.getBindingsForInstanceReturnsOnCall[i] = struct {
		result1 []cf.Binding
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudFoundryClient) GetInstance(arg1 string, arg2 *log.Logger) (cf.Instance, error) {
	fake.getInstanceMutex.Lock()
	ret, specificReturn := fake.getInstanceReturnsOnCall[len(fake.getInstanceArgsForCall)]
	fake.getInstanceArgsForCall = append(fake.getInstanceArgsForCall, struct {
		arg1 string
		arg2 *log.Logger
	}{arg1, arg2})
	fake.recordInvocation("GetInstance", []interface{}{arg1, arg2})
	fake.getInstanceMutex.Unlock()
	if fake.GetInstanceStub != nil {
		return fake.GetInstanceStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getInstanceReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCloudFoundryClient) GetInstanceCallCount() int {
	fake.getInstanceMutex.RLock()
	defer fake.getInstanceMutex.RUnlock()
	return len(fake.getInstanceArgsForCall)
}

func (fake *FakeCloudFoundryClient) GetInstanceCalls(stub func(string, *log.Logger) (cf.Instance, error)) {
	fake.getInstanceMutex.Lock()
	defer fake.getInstanceMutex.Unlock()
	fake.GetInstanceStub = stub
}

func (fake *FakeCloudFoundryClient) GetInstanceArgsForCall(i int) (string, *log.Logger) {
	fake.getInstanceMutex.RLock()
	defer fake.getInstanceMutex.RUnlock()
	argsForCall := fake.getInstanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudFoundryClient) GetInstanceReturns(result1 cf.Instance, result2 error) {
	fake.getInstanceMutex.Lock()
	defer fake.getInstanceMutex.Unlock()
	fake.GetInstanceStub = nil
	fake.getInstanceReturns = struct {
		result1 cf.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudFoundryClient) GetInstanceReturnsOnCall(i int, result1 cf.Instance, result2 error) {
	fake.getInstanceMutex.Lock()
	defer fake.getInstanceMutex.Unlock()
	fake.GetInstanceStub = nil
	if fake.getInstanceReturnsOnCall == nil {
		fake.getInstanceReturnsOnCall = make(map[int]struct {
			result1 cf.Instance
			result2 error
		})
	}
	fake.getInstanceReturnsOnCall[i] = struct {
		result1 cf.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudFoundryClient) GetInstancesOfServiceOffering(arg1 string, arg2 *log.Logger) ([]service.Instance, error) {
	fake.getInstancesOfServiceOfferingMutex.Lock()
	ret, specificReturn := fake.getInstancesOfServiceOfferingReturnsOnCall[len(fake.getInstancesOfServiceOfferingArgsForCall)]
	fake.getInstancesOfServiceOfferingArgsForCall = append(fake.getInstancesOfServiceOfferingArgsForCall, struct {
		arg1 string
		arg2 *log.Logger
	}{arg1, arg2})
	fake.recordInvocation("GetInstancesOfServiceOffering", []interface{}{arg1, arg2})
	fake.getInstancesOfServiceOfferingMutex.Unlock()
	if fake.GetInstancesOfServiceOfferingStub != nil {
		return fake.GetInstancesOfServiceOfferingStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getInstancesOfServiceOfferingReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCloudFoundryClient) GetInstancesOfServiceOfferingCallCount() int {
	fake.getInstancesOfServiceOfferingMutex.RLock()
	defer fake.getInstancesOfServiceOfferingMutex.RUnlock()
	return len(fake.getInstancesOfServiceOfferingArgsForCall)
}

func (fake *FakeCloudFoundryClient) GetInstancesOfServiceOfferingCalls(stub func(string, *log.Logger) ([]service.Instance, error)) {
	fake.getInstancesOfServiceOfferingMutex.Lock()
	defer fake.getInstancesOfServiceOfferingMutex.Unlock()
	fake.GetInstancesOfServiceOfferingStub = stub
}

func (fake *FakeCloudFoundryClient) GetInstancesOfServiceOfferingArgsForCall(i int) (string, *log.Logger) {
	fake.getInstancesOfServiceOfferingMutex.RLock()
	defer fake.getInstancesOfServiceOfferingMutex.RUnlock()
	argsForCall := fake.getInstancesOfServiceOfferingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudFoundryClient) GetInstancesOfServiceOfferingReturns(result1 []service.Instance, result2 error) {
	fake.getInstancesOfServiceOfferingMutex.Lock()
	defer fake.getInstancesOfServiceOfferingMutex.Unlock()
	fake.GetInstancesOfServiceOfferingStub = nil
	fake.getInstancesOfServiceOfferingReturns = struct {
		result1 []service.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudFoundryClient) GetInstancesOfServiceOfferingReturnsOnCall(i int, result1 []service.Instance, result2 error) {
	fake.getInstancesOfServiceOfferingMutex.Lock()
	defer fake.getInstancesOfServiceOfferingMutex.Unlock()
	fake.GetInstancesOfServiceOfferingStub = nil
	if fake.getInstancesOfServiceOfferingReturnsOnCall == nil {
		fake.getInstancesOfServiceOfferingReturnsOnCall = make(map[int]struct {
			result1 []service.Instance
			result2 error
		})
	}
	fake.getInstancesOfServiceOfferingReturnsOnCall[i] = struct {
		result1 []service.Instance
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudFoundryClient) GetServiceKeysForInstance(arg1 string, arg2 *log.Logger) ([]cf.ServiceKey, error) {
	fake.getServiceKeysForInstanceMutex.Lock()
	ret, specificReturn := fake.getServiceKeysForInstanceReturnsOnCall[len(fake.getServiceKeysForInstanceArgsForCall)]
	fake.getServiceKeysForInstanceArgsForCall = append(fake.getServiceKeysForInstanceArgsForCall, struct {
		arg1 string
		arg2 *log.Logger
	}{arg1, arg2})
	fake.recordInvocation("GetServiceKeysForInstance", []interface{}{arg1, arg2})
	fake.getServiceKeysForInstanceMutex.Unlock()
	if fake.GetServiceKeysForInstanceStub != nil {
		return fake.GetServiceKeysForInstanceStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getServiceKeysForInstanceReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCloudFoundryClient) GetServiceKeysForInstanceCallCount() int {
	fake.getServiceKeysForInstanceMutex.RLock()
	defer fake.getServiceKeysForInstanceMutex.RUnlock()
	return len(fake.getServiceKeysForInstanceArgsForCall)
}

func (fake *FakeCloudFoundryClient) GetServiceKeysForInstanceCalls(stub func(string, *log.Logger) ([]cf.ServiceKey, error)) {
	fake.getServiceKeysForInstanceMutex.Lock()
	defer fake.getServiceKeysForInstanceMutex.Unlock()
	fake.GetServiceKeysForInstanceStub = stub
}

func (fake *FakeCloudFoundryClient) GetServiceKeysForInstanceArgsForCall(i int) (string, *log.Logger) {
	fake.getServiceKeysForInstanceMutex.RLock()
	defer fake.getServiceKeysForInstanceMutex.RUnlock()
	argsForCall := fake.getServiceKeysForInstanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudFoundryClient) GetServiceKeysForInstanceReturns(result1 []cf.ServiceKey, result2 error) {
	fake.getServiceKeysForInstanceMutex.Lock()
	defer fake.getServiceKeysForInstanceMutex.Unlock()
	fake.GetServiceKeysForInstanceStub = nil
	fake.getServiceKeysForInstanceReturns = struct {
		result1 []cf.ServiceKey
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudFoundryClient) GetServiceKeysForInstanceReturnsOnCall(i int, result1 []cf.ServiceKey, result2 error) {
	fake.getServiceKeysForInstanceMutex.Lock()
	defer fake.getServiceKeysForInstanceMutex.Unlock()
	fake.GetServiceKeysForInstanceStub = nil
	if fake.getServiceKeysForInstanceReturnsOnCall == nil {
		fake.getServiceKeysForInstanceReturnsOnCall = make(map[int]struct {
			result1 []cf.ServiceKey
			result2 error
		})
	}
	fake.getServiceKeysForInstanceReturnsOnCall[i] = struct {
		result1 []cf.ServiceKey
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudFoundryClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteBindingMutex.RLock()
	defer fake.deleteBindingMutex.RUnlock()
	fake.deleteServiceInstanceMutex.RLock()
	defer fake.deleteServiceInstanceMutex.RUnlock()
	fake.deleteServiceKeyMutex.RLock()
	defer fake.deleteServiceKeyMutex.RUnlock()
	fake.getBindingsForInstanceMutex.RLock()
	defer fake.getBindingsForInstanceMutex.RUnlock()
	fake.getInstanceMutex.RLock()
	defer fake.getInstanceMutex.RUnlock()
	fake.getInstancesOfServiceOfferingMutex.RLock()
	defer fake.getInstancesOfServiceOfferingMutex.RUnlock()
	fake.getServiceKeysForInstanceMutex.RLock()
	defer fake.getServiceKeysForInstanceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCloudFoundryClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ deleter.CloudFoundryClient = new(FakeCloudFoundryClient)
